name: Release Binaries
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # allow creating releases
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
